version: "3.8"

services:
  backend:
    build: .
    ports:
      - "9000:9000"
    environment:
      - RUST_LOG=info
    volumes:
      - ./src:/app/src

  postgres:
    image: postgis/postgis:17-3.5
    env_file:
      - .env
    ports:
      - "5436:5436"
